name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and run Go program
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}	# æœåŠ¡å™¨åœ°å€
          username: ${{ secrets.USRNAME }} # ç™»é™†ç”¨æˆ·å
          key: ${{ secrets.KEY }} # æœåŠ¡å™¨ç§é’¥
          port: 22
          script: |
            cd /usr/local/robot-bot
            git checkout . && git pull || { echo "âŒ æ‹‰å–ä»£ç å¤±è´¥"; exit 1; }
            docker ps -a --format '{{.Names}}' | grep -w robot && docker stop robot && docker rm robot || echo "â„¹ï¸ å®¹å™¨ robot ä¸å­˜åœ¨ï¼Œè·³è¿‡"

            # æ„å»ºé•œåƒå¹¶éªŒè¯
            docker build -t myapp:v1 . || { echo "âŒ æ„å»ºå¤±è´¥"; exit 1; }
            docker images | grep myapp || { echo "âŒ é•œåƒä¸å­˜åœ¨"; exit 1; }

            # å¯åŠ¨å®¹å™¨
            docker run -d -p 8080:8080 --name robot myapp:v1 || { echo "âŒ è¿è¡Œå¤±è´¥"; exit 1; }
            echo "âœ… éƒ¨ç½²å®Œæˆ"
            # åˆ é™¤æ—§é•œåƒ
            docker image prune -a || echo "â„¹ï¸ æ²¡æœ‰æ—§é•œåƒéœ€è¦åˆ é™¤"
    